import "../globals.css";
import Toaster from "../../components/Shared/Toaster";
export const metadata = {
  title: "Login",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster></Toaster>
      </body>
    </html>
  );
}
