import "../globals.css";
import Toaster from "../../components/Shared/Toaster";
import AuthProvider from "../../providers/AuthProvider";
export const metadata = {
  title: "Login",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
        <Toaster></Toaster>
      </body>
    </html>
  );
}
