import { Inter } from "next/font/google";
import "../globals.css";
import Footer from "../../components/Shared/Footer";
import Navbar from "../../components/Shared/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CeMRD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <p className="">amar shonar bangla i lvoe yoyu</p>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
