"use client";
import { Inter } from "next/font/google";
import "../globals.css";
import Footer from "../../components/Shared/Footer";
import Navbar from "../../components/Shared/Navbar";
import AuthProvider from "../../providers/AuthProvider";
import { QueryClient, QueryClientProvider } from "react-query";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "CeMRD",
  description: "Generated by create next app",
};
const queryClient = new QueryClient();

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <p className="">amar shonar bangla i lvoe yoyu</p>
        <AuthProvider>
          <QueryClientProvider client={queryClient}>
            <Navbar></Navbar>
            {children}
          </QueryClientProvider>
        </AuthProvider>
        <Footer></Footer>
      </body>
    </html>
  );
}
